// This contains all upgrades and associated modifiers attached
"upgrades"
{
			"health_upgrade"
			{
						"npc_dota_hero_ancient_apparition_barebones"		"1"
						"soldier"	 	"1"
						"max_rank"	"3"
						"modifier"
						{
								"modifier_health_upgrade"			"1"
						}
			}
			"damage_upgrade"
			{
						"soldier"	 	"1"
						"max_rank"	"2"
						"modifier"
						{
								"modifier_damage_upgrade"			"1"
						}
			}
}